# YOUR NAME OR TITLE OF YOUR SITE
name: Balis Su

# YOUR BRAND/PERSONAL TAGLINE
tagline: WHAT UP

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/harsh98trivedi.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
  - Name: Rice $1
    URL: #
    Text_Color: '#ffffff'
    Color: '#3b5998'
    Icon-Class: fas fa-link

  - Name: Noodle $2
    URL: #
    Text_Color: '#ffffff'
    Color: '#DD2A7B'
    Icon-Class: fas fa-bath

  - Name: Vape $3
    URL: #
    Text_Color: '#ffffff'
    Color: '#000000'
    Icon-Class: fas fa-grav

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'No'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
